# Install all packages for this project in one shot

install.packages('xml2')
install.packages('magrittr')
install.packages('readxl')
install.packages('openxlsx')
install.packages('parallel')
install.packages('lme4')
install.packages('betareg')
install.packages('diverse')
# library(foreach)      # install.packages('foreach')
# library(doParallel)   # install.packages('doParallel')
# library(plyr)       # install.packages('plyr')
# library(rlist)      # install.packages('rlist')
install.packages('foreign')
install.packages('countrycode')
# library(WDI)          # install.packages('WDI')
install.packages('zoo')
install.packages('tidyr')
install.packages('ggplot2')
install.packages('interplot')
install.packages('scales')
install.packages('ggthemes')
# Always load dplyr last!  
install.packages('dplyr')
