# 4-Construct\prove-measures.R

# Goals of this script are:
#   - Take the measures generated by 4-Construct/construct-measures.R
#   - And/or the data generated by pivot-and-merge.R
#   - Produce evidence they are useful
#   - 

###################
# 1. Housekeeping #
###################

# Load functions
source(file="3-Unpack/parse-files-functions.R")
source(file="4-Construct/construct-measures-functions.R")

# Load classifications
source(file="3-Unpack/load-classifications.R")

############################################
# 2. Gather parameters about the job ahead #
############################################

# Obtain list of regions for which consolidated data is available
# regions_list <- generate_regions_list(data_parsed_directory)
# regions_list <- as.list("Adygeja_Resp")
regions_list <- as.list("Moskva")
regions_number <- length(regions_list)

# Define where outputs (eg graphs) should go
data_output_directory <- set_data_subdirectory(data_directory, data_download_date, "output")

##############################################
# 3. Load data, reshape it for graphs #
##############################################

# Loop over regions, processing them in turn (not needed for proving)
# for(r in 1:regions_number){
  r <- 1
  current_region <- as.character(regions_list[r])
  current_region_english <- generate_english_region_name(current_region)
  data_output_directory_region <- paste0(data_output_directory, current_region, "/")
  
    # Load the file of measures
    file_to_process <- paste0(data_output_directory, current_region, "/",
                              current_region, "_notifications_contracts_products_ungrouped_",
                              data_download_date, ".rda")
    load(file=file_to_process)
    
    file_to_process <- paste0(data_output_directory, current_region, "/",
                              current_region, "_notifications_contracts_products_grouped_",
                              data_download_date, ".rda")
    load(file=file_to_process)
  
    # Reshape for graphs below
    

##############################################
# 4. Create graphs #
##############################################
    

  ## HISTOGRAMS OF NOTIFICATION PRICES
  # Output three histograms for this region: listed price of notifications; same but only bottom three quartiles to show discontinuity at 500k; logged values across all dist
  notifications_maxPrice <- notifications_contracts_products_ungrouped %>%
                            filter(!TenderProcedureGroup %in% c("Olympic construction", "Preliminary selection") & !is.na(TenderProcedureGroup)) %>%
                            transmute(NotificationMaxPrice = NotificationLotCustomerRequirementMaxPrice,
                                      ProcedureGroup = TenderProcedureGroup)

  notifications_maxPrice_three_quartiles <- notifications_maxPrice %>%
    # filter(NotificationMaxPrice <= as.numeric(summary(notifications_maxPrice$NotificationMaxPrice)[5]))
    filter(NotificationMaxPrice <= as.numeric(quantile(notifications_maxPrice$NotificationMaxPrice, .81, na.rm = T)))

  # All notifications
  graph_title <- paste0("Distribution of initial listing prices for tenders in ", current_region_english, " (all quartiles)\n")
    graph_file_name <- paste0(data_output_directory_region, current_region, "_notification_maxPrice_histogram_raw_all_quartiles.pdf")
  notification_maxPrice_histogram_raw_all_quartiles <- ggplot(notifications_contracts_products_ungrouped, aes(x=NotificationLotCustomerRequirementMaxPrice)) +
                                                        geom_histogram(bins = 200) +
                                                        labs(title = graph_title, x = "\nInitial listing price (rubles)") +
                                                        scale_x_continuous(labels = comma) +
                                                        theme_bw() +
                                                        annotate("text", 
                                                                 x = 0.95*(max(notifications_contracts_products_ungrouped$NotificationLotCustomerRequirementMaxPrice, na.rm = T)), y = 0, label = "\nA few very large\ntenders in each\nregion skew the\ndistribution right", vjust = 0, hjust = 1)
  print(notification_maxPrice_histogram_raw_all_quartiles)
  ggsave(plot = notification_maxPrice_histogram_raw_all_quartiles, filename = graph_file_name, device = "pdf")
  
  # Bottom three quarters of notifications
  graph_title <- paste0("Distribution of initial listing price in ", current_region_english, ", by procedure type (excl. fourth quartile)\n")
    graph_file_name <- paste0(data_output_directory_region, current_region, "_notification_maxPrice_histogram_raw_three_quartiles.pdf")
  notification_maxPrice_histogram_raw_three_quartiles <- ggplot(notifications_maxPrice_three_quartiles, aes(x=NotificationMaxPrice, fill = ProcedureGroup)) +
    geom_histogram(bins = 200, show.legend = F) +
  # notification_maxPrice_histogram_raw_three_quartiles <- ggplot(notifications_maxPrice_three_quartiles, aes(x=NotificationMaxPrice, fill = ProcedureGroup)) +
    # geom_density(alpha = 0.2) +
    labs(title = graph_title, x = "\nInitial listing price (rubles)") +
    scale_x_continuous(labels = comma) +
    # scale_y_continuous(labels = NULL) +
    theme_bw() +
    scale_fill_tableau() +
    facet_wrap(~ ProcedureGroup, scales = "free_y", ncol = 1)
    #annotate("text", x = 450000, y = Inf, label = "\nRules change for\ntenders > 500k", vjust = 1, hjust = 1)
  print(notification_maxPrice_histogram_raw_three_quartiles)
  ggsave(plot = notification_maxPrice_histogram_raw_three_quartiles, filename = graph_file_name, device = "pdf", width = 8, height = 10)
  
  # All notifications, logged
  graph_title <- paste0("Distribution of initial listing prices (log base 10) for tenders in ", current_region_english, " (all quartiles)\n")
    graph_file_name <- paste0(data_output_directory_region, current_region, "_notification_maxPrice_histogram_log_all_quartiles.pdf")
  notification_maxPrice_histogram_log_all_quartiles <- ggplot(notifications_maxPrice, aes(x=NotificationMaxPrice)) +
    geom_histogram(bins = 200) +
    labs(title = graph_title, x = "\nInitial listing price (rubles, log base 10)") +
    scale_x_continuous(labels = comma, trans = "log10") +
    theme_bw() +
    annotate("text", x = 350000, y = Inf, label = "\nRules change for\ntenders > 500k", vjust = 1, hjust = 1)
  print(notification_maxPrice_histogram_log_all_quartiles)
  ggsave(plot = notification_maxPrice_histogram_log_all_quartiles, filename = graph_file_name, device = "pdf")
  
  
  # Quick graph of price change
  hist(notifications_contracts_products_ungrouped$PriceChangePercentageNoOutliers, breaks = 100)
  
  # Can also facet with greyed-out underlying data, perhaps for comparing two agencies
  # http://docs.ggplot2.org/current/facet_wrap.html
  
  
  ## STACKED BAR CHART OF PROCEDURE CHOICE BY AGENCY
  procedure_choice_by_agency <- notifications_contracts_products_ungrouped %>%
    group_by(ContractCustomerRegNum, TenderProcedureGroup) %>%
      summarize(NotificationsPerProcedure = n()) %>% ungroup() %>%
    filter(TenderProcedureGroup %in% c("Open electronic auction", "Open tender", "Request for quotes")) %>%
    spread(key = TenderProcedureGroup, value = NotificationsPerProcedure, fill = 0) %>%
    mutate(`Total notifications` = (`Open electronic auction` + `Open tender` + `Request for quotes`)) %>%
    filter(`Total notifications` > 2) %>%
    transmute(Agency = ContractCustomerRegNum,
              # `Other` = Other/`Total notifications`,
              `Open electronic auction` = `Open electronic auction`/`Total notifications`,
              `Open tender` = `Open tender`/`Total notifications`,
              `Request for quotes` = `Request for quotes`/`Total notifications`,
              DominantProcedure = ifelse(`Open electronic auction` == 1, "0 Open electronic auction", 
                                         ifelse(`Open tender` == 1, "1 Open tender", 
                                                ifelse(`Request for quotes` == 1, "2 Request for quotes", "3 None")))) %>%
  # slice(1:20) %>%
    arrange(DominantProcedure, -`Open electronic auction`, -`Open tender`, -`Request for quotes`) %>%
    # arrange(DominantProcedure, -`Request for quotes`, -`Open tender`, -`Open electronic auction`, -Other) %>%
    # arrange(-`Open tender`, -`Open electronic auction`, -`Request for quotes`, -Other) %>%
    # arrange(-`Open tender`, `Request for quotes`, -`Open electronic auction`, -Other) %>%
    mutate(SortByProportionHigher = row_number(),
           ProportionOfAllAgencies = SortByProportionHigher/length(unique(notifications_contracts_products_ungrouped$ContractCustomerRegNum))) %>%
    gather(key = `Procedure`, value = Proportion, -Agency, -SortByProportionHigher, -ProportionOfAllAgencies, -DominantProcedure) %>%
    filter(`Procedure` != "Other")
  
  procedure_choice_by_agency$`Procedure` <- factor(procedure_choice_by_agency$`Procedure`,
                                                                   levels = c("Open electronic auction", "Open tender",
                                                                              "Request for quotes", "Other"))
  
  # Some variables to help label axes
  maximum_agency_number <- max(procedure_choice_by_agency$SortByProportionHigher)
  all_lower_discretion_agency_number <- max(procedure_choice_by_agency[procedure_choice_by_agency$DominantProcedure == "0 Open electronic auction", "SortByProportionHigher"])
    all_lower_discretion_agency_label <- round(all_lower_discretion_agency_number/maximum_agency_number, digits = 2)
  all_medium_discretion_agency_number <- max(procedure_choice_by_agency[procedure_choice_by_agency$DominantProcedure == "1 Open tender", "SortByProportionHigher"])
    all_medium_discretion_agency_label <- round(all_medium_discretion_agency_number/maximum_agency_number, digits = 2)
  all_higher_discretion_agency_number <- max(procedure_choice_by_agency[procedure_choice_by_agency$DominantProcedure == "2 Request for quotes", "SortByProportionHigher"])
    all_higher_discretion_agency_label <- round(all_higher_discretion_agency_number/maximum_agency_number, digits = 2)
    
  graph_title <- paste0("Choice of procurement procedure by agencies in ", current_region_english, ",\n2011-2015 (agencies with at least three purchases)\n")
    graph_file_name <- paste0(data_output_directory_region, current_region, "_procedure_choice.pdf")
  procedure_choice_by_agency_graph <- procedure_choice_by_agency %>%
    ggplot(aes(x = SortByProportionHigher, y = Proportion, fill = `Procedure`)) +
    # ggplot(aes(x = SortByProportionHigher, fill = `Proportion of\nprocedures`)) +
    geom_bar(stat = "identity", width = 1) +
    # geom_histogram(bins = 50) +
    coord_flip() +
    theme_few() +
    scale_fill_tableau() +
    labs(title = graph_title,
         x = "Proportion of individual agencies\n",
         y = "\nProportion of agency purchases") +
    # theme(axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
    scale_x_continuous(breaks = c(0, all_medium_discretion_agency_number, all_higher_discretion_agency_number, maximum_agency_number, maximum_agency_number/2, 3*maximum_agency_number/4),
                       labels = c("0", all_medium_discretion_agency_label, all_higher_discretion_agency_label, "1", "0.5", "0.75")) +
    theme(legend.position="bottom") +
    theme(legend.title=element_blank())
  print(procedure_choice_by_agency_graph)
  ggsave(plot = procedure_choice_by_agency_graph, filename = graph_file_name, device = "pdf", limitsize = T)
  
  
 
    
  ## AUCTION EFFICIENCY BY AGENCY (grouped products)
  auction_efficiency_by_agency <- notifications_contracts_products_grouped %>%
    filter(ContractCurrencyCode == "RUB" & ContractPrice > 0 & NotificationLotCustomerRequirementMaxPrice > 0) %>%
    transmute(AgencyID = ContractCustomerRegNum,
              `Initial price` = NotificationLotCustomerRequirementMaxPrice,
              `Final price` = ContractPrice,
              `Auction efficiency` = PriceChangePercentageNoOutliers,
              `Class of product` = ContractProductCodeLevel1,
              `Procedure type` = TenderProcedureDiscretion) %>%
    filter(!is.na(`Auction efficiency`) & `Final price` >= 1000) %>%
    group_by(AgencyID) %>%
    # group_by(AgencyID, `Class of product`) %>%
    # group_by(AgencyID, `Class of product`, `Procedure type`) %>%
    summarize(`Median auction efficiency` = median(`Auction efficiency`),
              `Mean auction efficiency` = mean(`Auction efficiency`),
                `Total spent` = sum(`Final price`),
                `Total spent (square root)` = sqrt(`Total spent`),
                `Total spent (log)` = log10(`Total spent`),
                `Total spent (inverse)` = 1/(`Total spent`),
                `Number of purchases` = n()) %>%
    filter(`Total spent` >= 100000 & `Total spent` <= 100000000000 & `Number of purchases` > 100) # Thresholds for agencies alone
    # filter(`Total spent` >= 100000 & `Total spent` <= 10000000000 & `Number of purchases` > 10)     # Thresholds for agency/product pairs
    # filter(`Total spent` >= 10000 & `Total spent` <= 1000000000 & `Number of purchases` > 2)      # Thresholds for agency/product/procedure pairs
  
  # http://zakupki.gov.ru/pgz/public/action/orders/info/common_info/show?notificationId=694772
  # Classic example of highly efficient auction: max price 1.5 million, lowest bidder 74.5k (of course, given range of bids, subject to "bad good" problem)

  plot(auction_efficiency_by_agency$`Total spent`, auction_efficiency_by_agency$`Median auction efficiency`)
    lines(lowess(auction_efficiency_by_agency$`Total spent`, auction_efficiency_by_agency$`Median auction efficiency`), col = "blue")
  plot(auction_efficiency_by_agency$`Total spent (square root)`, auction_efficiency_by_agency$`Median auction efficiency`)
    lines(lowess(auction_efficiency_by_agency$`Total spent (square root)`, auction_efficiency_by_agency$`Median auction efficiency`), col = "blue")
  plot(auction_efficiency_by_agency$`Total spent (log)`, auction_efficiency_by_agency$`Median auction efficiency`)
    lines(lowess(auction_efficiency_by_agency$`Total spent (log)`, auction_efficiency_by_agency$`Median auction efficiency`), col = "blue")
  # plot(auction_efficiency_by_agency$`Total spent (inverse)`, auction_efficiency_by_agency$`Median auction efficiency`)
  
  # Two graphs here: auction efficiency vs spend  
    
  graph_title <- paste0("Efficiency of median auction vs total spent\nby agencies in ", current_region_english, ", 2011-2015\n")
    graph_file_name <- paste0(data_output_directory_region, current_region, "_auction_efficiency_vs_spend.pdf")
    auction_efficiency_vs_spend_graph <- auction_efficiency_by_agency %>%
      ggplot(aes(x = `Total spent (log)`, y = `Median auction efficiency`)) +
      geom_point(aes(size = `Number of purchases`), alpha = 1/2) +
      stat_smooth(se = F, col = "orange") +
      theme_few() +
      scale_fill_tableau() +
      labs(title = graph_title,
           x = "\nTotal spent by agency (log scale)\n",
           y = "Median auction efficiency\n") +
      theme(legend.position="bottom")
    print(auction_efficiency_vs_spend_graph)
    ggsave(plot = auction_efficiency_vs_spend_graph, filename = graph_file_name, device = "pdf", limitsize = T)
    
  
  # And auction efficiency vs procedure
  
  # And contract starting value vs ending value?
    
    
  efficiency_vs_spend <- lm(`Median auction efficiency` ~ `Total spent`, data = auction_efficiency_by_agency)
  summary(efficiency_vs_spend)
  # No matter which rules you apply to exclude extreme values, grouping by agency/product/procedure, 
  # relationship is positive and significant: spending more associated with lower auction efficiency
  # 1,000,000,000 increase in spending associated with 1.5-2.0 percentage point decrease in efficiency under different groupings
  # But clearly spending less not sufficient for higher efficiency, triangular pattern
  
  
  # % CALCULATE AVERAGE GAP BY HIGH-LEVEL PRODUCT CODE, THEN AGENCY DEVIATIONS
  # % DOES VARIANCE OF THE GAP TELL US ANYTHING?
  # % MODEL THE GAP AS FUNCTION OF SOME THINGS, LOOK AT RESIDUALS?
  # % Can go within agency, see proportion of purchases where padding+restriction
  # 
  
  
# } # Closes control loop over regions_list

# ENDS